# Generated by Django 4.0.1 on 2022-01-21 10:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_app', '0003_alter_chapter_options_remove_chapter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
