# Generated by Django 4.0.1 on 2022-01-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_app', '0006_alter_chapter_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
