# Generated by Django 4.0.1 on 2022-01-23 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_app', '0007_book_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pub_date',
            new_name='date_of_publication',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_rest_app.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.BooleanField(default=False, help_text='Just how the book is going to be published now'),
        ),
    ]
