# Generated by Django 4.0.1 on 2022-01-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_app', '0008_rename_pub_date_book_date_of_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Just how the book is going to be published now'),
        ),
    ]
